### ISSUE TITLE
Release modda Segmentation Fault

### ISSUE THREAD

**Issue by isil-oz** [parsiyte/GPPRMon#1]
debug modunda ("source setup_environment debug" komutundan sonra) derlediğimizde problem yokken release modda ("source setup_environment" sonrasında) derlediğimizde kısa bir süre çalıştıktan sonra "Segmentation Fault" hatası alıyoruz.

**Comment by topcuburak** [comment]
The problem was related to the changes that I made in AccelWattch. Now, you can compile & build the simulator in release mode (source setup_environment release || source setup_environment), and I hope you won't see the same problem again. Thank you for letting me know Professor. If you will face any problems in the future, please let me know again.
